# Generated by Django 3.1.7 on 2021-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('courier_type', models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4)),
                ('regions', models.ManyToManyField(to='api_v1.Region')),
                ('working_hours', models.ManyToManyField(to='api_v1.WorkingHour')),
            ],
        ),
    ]
