# Generated by Django 3.1.7 on 2021-03-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.PositiveIntegerField()),
                ('item_name', models.CharField(max_length=100)),
            ],
        ),
    ]
