# Generated by Django 3.1.7 on 2021-03-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='id',
            new_name='courier_id',
        ),
    ]
