# Generated by Django 3.1.7 on 2021-03-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='interval',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
